[custom]

; 直连（去重合并）
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,[]GEOIP,CN

; 💬 OpenAi
ruleset=💬 OpenAi,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list

; 广告
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list

; 微软
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list

; 苹果
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list

; 通讯/流媒体
ruleset=📲 电报消息,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🎥 奈飞视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=📹 油管视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🎬 tiktok,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/TikTok.list

; 游戏
ruleset=🎮 Epic,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🎮 橙子,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
ruleset=🎮 索尼,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=🎮 Steam,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🎮 任天堂,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list

; Google
ruleset=📢 谷歌,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Google.list

; GitHub & Docker
ruleset=💻 GitHub,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Github.list
ruleset=⚙️ Docker,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Docker.list

; 视频站
ruleset=📺 巴哈姆特,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list

; 媒体
ruleset=🌏 国内媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list

; GFW
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list

; 最终
ruleset=🐟 漏网之鱼,[]FINAL

; ===== 基础核心组 =====
custom_proxy_group=🎯 全球直连`select`[]DIRECT
custom_proxy_group=♻️ 自动选择`url-test`.*`https://cp.cloudflare.com/generate_204`300,3,150
custom_proxy_group=🚀 直连选择`url-test`^(?!.*中继).*`https://cp.cloudflare.com/generate_204`300,3,150
custom_proxy_group=🚀 中继选择`url-test`.*中继.*`https://cp.cloudflare.com/generate_204`300,3,150
custom_proxy_group=🚀 手动切换`select`.*

; ===== 专用组 =====
custom_proxy_group=🔯 故障转移`fallback`.*`https://cp.cloudflare.com/generate_204`180
custom_proxy_group=🔮 负载均衡`load-balance`.*`https://cp.cloudflare.com/generate_204`300,3,150
custom_proxy_group=🎥 奈飞节点`select`(NF|奈飞|解锁|Netflix|NETFLIX|Media)
custom_proxy_group=💬 OpenAi(专用)`select`(?i).*AI.*

; ===== 业务分流 =====
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT
custom_proxy_group=💬 OpenAi`select`[]🚀 直连选择`[]🚀 中继选择`[]🚀 手动切换`[]🔯 故障转移`[]🔮 负载均衡`[]♻️ 自动选择`[]💬 OpenAi(专用)
custom_proxy_group=📹 油管视频`select`[]🚀 直连选择`[]🚀 中继选择`[]🚀 手动切换`[]🔯 故障转移`[]🔮 负载均衡`[]♻️ 自动选择
custom_proxy_group=📲 电报消息`select`[]🚀 直连选择`[]🚀 中继选择`[]🚀 手动切换`[]🔯 故障转移`[]🔮 负载均衡`[]♻️ 自动选择
custom_proxy_group=🎥 奈飞视频`select`[]🚀 直连选择`[]🚀 中继选择`[]🚀 手动切换`[]🔯 故障转移`[]🔮 负载均衡`[]♻️ 自动选择`[]🎥 奈飞节点
custom_proxy_group=📺 巴哈姆特`select`[]🚀 直连选择`[]🚀 中继选择`[]🚀 手动切换`[]🔯 故障转移`[]🔮 负载均衡`[]♻️ 自动选择
custom_proxy_group=🎬 tiktok`select`[]🚀 直连选择`[]🚀 中继选择`[]🚀 手动切换`[]🔯 故障转移`[]🔮 负载均衡`[]♻️ 自动选择
custom_proxy_group=🌍 国外媒体`select`[]🚀 直连选择`[]🚀 中继选择`[]🚀 手动切换`[]🔯 故障转移`[]🔮 负载均衡`[]♻️ 自动选择
custom_proxy_group=📢 谷歌`select`[]🚀 直连选择`[]🚀 中继选择`[]🚀 手动切换`[]🔯 故障转移`[]🔮 负载均衡`[]♻️ 自动选择
custom_proxy_group=💻 GitHub`select`[]🚀 直连选择`[]🚀 中继选择`[]🚀 手动切换`[]🔯 故障转移`[]🔮 负载均衡`[]♻️ 自动选择
custom_proxy_group=⚙️ Docker`select`[]🚀 直连选择`[]🚀 中继选择`[]🚀 手动切换`[]🔯 故障转移`[]🔮 负载均衡`[]♻️ 自动选择
custom_proxy_group=🎮 Epic`select`[]🎯 全球直连`[]🚀 直连选择`[]🚀 中继选择`[]🚀 手动切换`[]🔯 故障转移`[]🔮 负载均衡`[]♻️ 自动选择
custom_proxy_group=🎮 橙子`select`[]🎯 全球直连`[]🚀 直连选择`[]🚀 中继选择`[]🚀 手动切换`[]🔯 故障转移`[]🔮 负载均衡`[]♻️ 自动选择
custom_proxy_group=🎮 索尼`select`[]🎯 全球直连`[]🚀 直连选择`[]🚀 中继选择`[]🚀 手动切换`[]🔯 故障转移`[]🔮 负载均衡`[]♻️ 自动选择
custom_proxy_group=🎮 Steam`select`[]🎯 全球直连`[]🚀 直连选择`[]🚀 中继选择`[]🚀 手动切换`[]🔯 故障转移`[]🔮 负载均衡`[]♻️ 自动选择
custom_proxy_group=🎮 任天堂`select`[]🎯 全球直连`[]🚀 直连选择`[]🚀 中继选择`[]🚀 手动切换`[]🔯 故障转移`[]🔮 负载均衡`[]♻️ 自动选择
custom_proxy_group=🍎 苹果服务`select`[]🎯 全球直连`[]🚀 直连选择`[]🚀 中继选择`[]🚀 手动切换`[]🔯 故障转移`[]🔮 负载均衡`[]♻️ 自动选择
custom_proxy_group=Ⓜ️ 微软服务`select`[]🎯 全球直连`[]🚀 直连选择`[]🚀 中继选择`[]🚀 手动切换`[]🔯 故障转移`[]🔮 负载均衡`[]♻️ 自动选择
custom_proxy_group=🌏 国内媒体`select`[]🎯 全球直连`[]🚀 直连选择`[]🚀 中继选择`[]🚀 手动切换`[]🔯 故障转移`[]🔮 负载均衡`[]♻️ 自动选择
custom_proxy_group=🚀 节点选择`select`[]🎯 全球直连`[]🚀 直连选择`[]🚀 中继选择`[]🚀 手动切换`[]🔯 故障转移`[]🔮 负载均衡`[]♻️ 自动选择
custom_proxy_group=🐟 漏网之鱼`select`[]🎯 全球直连`[]🚀 直连选择`[]🚀 中继选择`[]🚀 手动切换`[]🔯 故障转移`[]🔮 负载均衡`[]♻️ 自动选择

enable_rule_generator=true
overwrite_original_rules=true
